[providers]
nodejs = "18"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
dependsOn = []
cmds = [
  "npm install",
  "npm run install-deps"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start" 