[phases.setup]
cmds = ['echo "=== SETUP PHASE ==="']

[phases.install] 
cmds = [
  'echo "=== INSTALLING DEPENDENCIES ==="',
  'npm install',
  'echo "=== BUILDING FRONTEND ==="',
  'cd frontend && npm install',
  'cd frontend && npm run build',
  'echo "=== COPYING BUILD TO BACKEND ==="',
  'cp -r frontend/build backend/public',
  'echo "=== INSTALLING BACKEND DEPS ==="',
  'cd backend && npm install'
]

[phases.build]
cmds = ['echo "=== BUILD PHASE COMPLETE ==="']

[start]
cmd = 'cd backend && node src/server.js' 