providers = ["node"]

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "false"

[phases.install]
cmds = [
  "npm install",
  "cd backend && npm install",
  "cd frontend && npm install"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "cd frontend && npm run build"
]

[start]
cmd = "npm start" 