export { default as Dashboard } from './Dashboard';
export { default as Animals } from './Animals';
export { default as AnimalForm } from './AnimalForm';
export { default as AnimalDetail } from './AnimalDetail';
export { default as Feeds } from './Feeds';
export { default as FeedForm } from './FeedForm';
export { default as FeedDetail } from './FeedDetail';
export { default as Comparison } from './Comparison';
export { default as Calculator } from './Calculator'; 